name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          find .
        working-directory: ${{ github.action_path }}
