name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ${{ github.action_path }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - run: |
          find .
        working-directory: /home/runner/work
